### ISSUE TITLE
move workflows to github actions

### ISSUE THREAD

**Issue by jspaaks** [citation-file-format/cff-converter-python#164]
- [x] unit tests: PR #183
- [x] filename consistency tests: PR #190
- [ ] live tests: issue #185

**Comment by jspaaks** [comment]
The last remaining issue (running live tests on github actions) has its own dedicated issue (#185). Closing this one.
